# Configure appveyor for builds.

environment:
  # Install appropriate conda here based on TARGET_ARCH
  CONDA_INSTALL_LOCN: "C:\\conda"

  # These installs are needed on windows but not other platforms.
  INSTALL_ON_WINDOWS: "patch psutil"

  BINSTAR_TOKEN:
    secure: eSsu75dpqknmh2NnrfPASDSvzojBRSyoyW9ZdF5VauukhWxmYHbW8E5UE2ZmYnxT

  PYPI_PASSWORD:
    secure: Xtu8c7MEUwNUJN08oehTSQ==

  PYPI_USER:
    secure: hSkBSpb86gg/J+PxsYWbeg==
  matrix:
    # Unfortunately, compiler/SDK configuration for 64 bit builds depends on
    # python version. Right now conda build does not configure the SDK, and
    # the appveyor setup only sets up the SDK once, so separate by python
    # versions.
    - TARGET_ARCH: "x64"
      CONDA_PY: "3.7"
      CONDA_INSTALL_LOCN: "C:\\Miniconda37-x64"
    - TARGET_ARCH: "x64"
      CONDA_PY: "3.6"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - TARGET_ARCH: "x64"
      CONDA_PY: "3.5"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"

    # 32-bit builds
    - TARGET_ARCH: "x86"
      CONDA_PY: "3.7"
      CONDA_INSTALL_LOCN: "C:\\Miniconda37"
    - TARGET_ARCH: "x86"
      CONDA_PY: "3.6"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36"
    - TARGET_ARCH: "x86"
      CONDA_PY: "3.5"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35"

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

install:
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    # Gets us vpnotebook
    - cmd: conda config --add channels vpython

    - cmd: conda config --set always_yes true
    - cmd: conda update --quiet conda



    - cmd: conda install --quiet jinja2 conda-build anaconda-client cython wheel %INSTALL_ON_WINDOWS%

    - conda create --quiet -n wheel-build python=%CONDA_PY% wheel cython
    - conda info -a

# Skip .NET project specific build phase.
build: off

test_script:
    # Not much of a real test yet, just try to build myself...
    - conda build --quiet vpython.recipe
    # ...and build a wheel, in the test environment so we have the right
    # python version.
    # Write the output file location to a file...
    - conda build --output vpython.recipe > to_upload.txt
    - set /P BUILT_PACKAGE=<to_upload.txt
    - type to_upload.txt
    - for /F "delims=" %%i in (to_upload.txt) do set "BUILT_PACKAGE=%%i"
    - echo %BUILT_PACKAGE%
    - if NOT EXIST %BUILT_PACKAGE% exit /b 1
    - for %%F in (%BUILT_PACKAGE%) do set dirname=%%~dpF
    - echo %dirname%
    - activate wheel-build
    - python setup.py bdist_wheel"
    - deactivate

on_success:
    # Make sure appveyor still knows about conda...
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - set upload_builds=
    - if "%APPVEYOR_REPO_TAG%"=="true" set upload_builds=1
    - python .ci-support\upload-label.py > label.txt
    - set /P UPLOAD_LABEL=<label.txt
    - echo %UPLOAD_LABEL%
    # If this build is because of a tag on master make the conda package and upload it.
    - cmd: if defined upload_builds anaconda -t %BINSTAR_TOKEN% upload -u vpython -l %UPLOAD_LABEL% %BUILT_PACKAGE%
    - cmd: pip install twine
    - cmd: if defined upload_builds twine upload -u %PYPI_USER% -p %PYPI_PASSWORD% dist\*
