package:
  name: vpython
  version: 7.4.7

source:
  path: ../
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - vpython = vpython:main
    #
    # Would create an entry point called vpython that calls vpython.main()

  script: python setup.py install --single-version-externally-managed --record record.txt # [ not win ]
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - jupyter
    - ujson
    - cython
    - wheel

  run:
    - python
    - jupyter
    - ujson
    - autobahn >=18.8.2 # [py37]
    - autobahn #  [not py2k and not py34 and not py37]
    - numpy
    - ipykernel <5

outputs:
    - type: wheel   # [not win]
    - type: conda
      name: vpython

about:
  home: http://vpython.org
  license: MIT
  summary: 'VPython for Jupyter Notebook'
