on:
  schedule:
    # Run once a day at 20:10 UTC
    # But for now every hour on 35.
    - cron: '35 * * * *'

jobs:
  copy_packages:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: 3.7

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install anaconda-client

    - name: Perform copy
      shell: bash -l {0}
      run: |
        git clone git://github.com/glue-viz/conda-sync.git
        mv conda-sync/sync.py .
        python drive_copy.py
